//
//  MyStyleKit.swift
//  Concurrency
//
//  Created by Chris Mendez on 4/20/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class MyStyleKit : NSObject {

    //// Drawing Methods

    public class func drawCanvas2() {
        //// Color Declarations
        let fillColor2 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Group 2
        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(74.72, 73.84))
        bezierPath.addCurveToPoint(CGPointMake(81.85, 71.09), controlPoint1: CGPointMake(77.47, 73.84), controlPoint2: CGPointMake(79.96, 72.78))
        bezierPath.addCurveToPoint(CGPointMake(88.98, 73.84), controlPoint1: CGPointMake(83.74, 72.78), controlPoint2: CGPointMake(86.23, 73.84))
        bezierPath.addCurveToPoint(CGPointMake(99.67, 63.27), controlPoint1: CGPointMake(94.88, 73.84), controlPoint2: CGPointMake(99.67, 69.1))
        bezierPath.addCurveToPoint(CGPointMake(88.98, 52.7), controlPoint1: CGPointMake(99.67, 57.43), controlPoint2: CGPointMake(94.88, 52.7))
        bezierPath.addCurveToPoint(CGPointMake(81.85, 55.44), controlPoint1: CGPointMake(86.23, 52.7), controlPoint2: CGPointMake(83.74, 53.76))
        bezierPath.addCurveToPoint(CGPointMake(74.72, 52.7), controlPoint1: CGPointMake(79.96, 53.76), controlPoint2: CGPointMake(77.47, 52.7))
        bezierPath.addCurveToPoint(CGPointMake(64.03, 63.27), controlPoint1: CGPointMake(68.82, 52.7), controlPoint2: CGPointMake(64.03, 57.43))
        bezierPath.addCurveToPoint(CGPointMake(74.72, 73.84), controlPoint1: CGPointMake(64.03, 69.1), controlPoint2: CGPointMake(68.82, 73.84))
        bezierPath.closePath()
        fillColor2.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(106.8, 17.47))
        bezier2Path.addLineToPoint(CGPointMake(21.25, 17.47))
        bezier2Path.addCurveToPoint(CGPointMake(14.12, 24.51), controlPoint1: CGPointMake(17.31, 17.47), controlPoint2: CGPointMake(14.12, 20.62))
        bezier2Path.addLineToPoint(CGPointMake(14.12, 45.65))
        bezier2Path.addLineToPoint(CGPointMake(106.8, 45.65))
        bezier2Path.addLineToPoint(CGPointMake(106.8, 80.88))
        bezier2Path.addLineToPoint(CGPointMake(56.9, 80.88))
        bezier2Path.addLineToPoint(CGPointMake(56.9, 87.93))
        bezier2Path.addLineToPoint(CGPointMake(106.8, 87.93))
        bezier2Path.addCurveToPoint(CGPointMake(113.93, 80.88), controlPoint1: CGPointMake(110.75, 87.93), controlPoint2: CGPointMake(113.93, 84.78))
        bezier2Path.addLineToPoint(CGPointMake(113.93, 24.51))
        bezier2Path.addCurveToPoint(CGPointMake(106.8, 17.47), controlPoint1: CGPointMake(113.93, 20.62), controlPoint2: CGPointMake(110.75, 17.47))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(21.25, 24.51))
        bezier2Path.addLineToPoint(CGPointMake(106.8, 24.51))
        bezier2Path.addLineToPoint(CGPointMake(106.8, 31.56))
        bezier2Path.addLineToPoint(CGPointMake(21.25, 31.56))
        bezier2Path.addLineToPoint(CGPointMake(21.25, 24.51))
        bezier2Path.closePath()
        fillColor2.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(24.81, 52.7))
        bezier3Path.addCurveToPoint(CGPointMake(-0.14, 77.36), controlPoint1: CGPointMake(11.03, 52.7), controlPoint2: CGPointMake(-0.14, 63.74))
        bezier3Path.addCurveToPoint(CGPointMake(24.81, 102.02), controlPoint1: CGPointMake(-0.14, 90.98), controlPoint2: CGPointMake(11.03, 102.02))
        bezier3Path.addCurveToPoint(CGPointMake(49.77, 77.36), controlPoint1: CGPointMake(38.6, 102.02), controlPoint2: CGPointMake(49.77, 90.98))
        bezier3Path.addCurveToPoint(CGPointMake(24.81, 52.7), controlPoint1: CGPointMake(49.77, 63.74), controlPoint2: CGPointMake(38.6, 52.7))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(39.94, 87.32))
        bezier3Path.addLineToPoint(CGPointMake(34.9, 92.31))
        bezier3Path.addLineToPoint(CGPointMake(24.81, 82.34))
        bezier3Path.addLineToPoint(CGPointMake(14.73, 92.31))
        bezier3Path.addLineToPoint(CGPointMake(9.69, 87.32))
        bezier3Path.addLineToPoint(CGPointMake(19.77, 77.36))
        bezier3Path.addLineToPoint(CGPointMake(9.69, 67.4))
        bezier3Path.addLineToPoint(CGPointMake(14.73, 62.41))
        bezier3Path.addLineToPoint(CGPointMake(24.81, 72.38))
        bezier3Path.addLineToPoint(CGPointMake(34.9, 62.41))
        bezier3Path.addLineToPoint(CGPointMake(39.94, 67.4))
        bezier3Path.addLineToPoint(CGPointMake(29.85, 77.36))
        bezier3Path.addLineToPoint(CGPointMake(39.94, 87.32))
        bezier3Path.closePath()
        fillColor2.setFill()
        bezier3Path.fill()
    }

    public class func drawCanvas1() {
        //// Color Declarations
        let fillColor2 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Group 2
        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(98.26, 58.76))
        bezierPath.addLineToPoint(CGPointMake(98.26, 58.76))
        bezierPath.addCurveToPoint(CGPointMake(58.57, 98.45), controlPoint1: CGPointMake(98.26, 80.65), controlPoint2: CGPointMake(80.45, 98.45))
        bezierPath.addCurveToPoint(CGPointMake(26.84, 82.55), controlPoint1: CGPointMake(45.59, 98.45), controlPoint2: CGPointMake(34.08, 92.19))
        bezierPath.addLineToPoint(CGPointMake(38.72, 70.66))
        bezierPath.addLineToPoint(CGPointMake(3, 70.66))
        bezierPath.addLineToPoint(CGPointMake(3, 106.39))
        bezierPath.addLineToPoint(CGPointMake(15.51, 93.87))
        bezierPath.addCurveToPoint(CGPointMake(58.57, 114.32), controlPoint1: CGPointMake(25.7, 106.35), controlPoint2: CGPointMake(41.2, 114.32))
        bezierPath.addCurveToPoint(CGPointMake(114.13, 58.76), controlPoint1: CGPointMake(89.25, 114.32), controlPoint2: CGPointMake(114.13, 89.45))
        bezierPath.addLineToPoint(CGPointMake(98.26, 58.76))
        bezierPath.addLineToPoint(CGPointMake(98.26, 58.76))
        bezierPath.closePath()
        fillColor2.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(101.61, 23.65))
        bezier2Path.addCurveToPoint(CGPointMake(58.56, 3.19), controlPoint1: CGPointMake(91.43, 11.17), controlPoint2: CGPointMake(75.93, 3.19))
        bezier2Path.addCurveToPoint(CGPointMake(3, 58.76), controlPoint1: CGPointMake(27.88, 3.19), controlPoint2: CGPointMake(3, 28.07))
        bezier2Path.addLineToPoint(CGPointMake(18.87, 58.76))
        bezier2Path.addCurveToPoint(CGPointMake(58.56, 19.07), controlPoint1: CGPointMake(18.87, 36.87), controlPoint2: CGPointMake(36.68, 19.07))
        bezier2Path.addCurveToPoint(CGPointMake(90.3, 34.96), controlPoint1: CGPointMake(71.53, 19.07), controlPoint2: CGPointMake(83.05, 25.32))
        bezier2Path.addLineToPoint(CGPointMake(78.41, 46.85))
        bezier2Path.addLineToPoint(CGPointMake(114.13, 46.85))
        bezier2Path.addLineToPoint(CGPointMake(114.13, 11.14))
        bezier2Path.addLineToPoint(CGPointMake(101.61, 23.65))
        bezier2Path.closePath()
        fillColor2.setFill()
        bezier2Path.fill()
    }

    public class func drawCanvas3() {
        //// Color Declarations
        let fillColor2 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Group 2
        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(53.72, 84.61))
        bezierPath.addCurveToPoint(CGPointMake(55.44, 90.43), controlPoint1: CGPointMake(54.8, 86.3), controlPoint2: CGPointMake(55.44, 88.29))
        bezierPath.addCurveToPoint(CGPointMake(55.41, 91.12), controlPoint1: CGPointMake(55.44, 90.66), controlPoint2: CGPointMake(55.42, 90.89))
        bezierPath.addLineToPoint(CGPointMake(64.96, 91.12))
        bezierPath.addCurveToPoint(CGPointMake(64.92, 90.43), controlPoint1: CGPointMake(64.95, 90.89), controlPoint2: CGPointMake(64.92, 90.66))
        bezierPath.addCurveToPoint(CGPointMake(66.64, 84.61), controlPoint1: CGPointMake(64.92, 88.29), controlPoint2: CGPointMake(65.56, 86.3))
        bezierPath.addLineToPoint(CGPointMake(53.72, 84.61))
        bezierPath.closePath()
        fillColor2.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(73.99, 38.31))
        bezier2Path.addCurveToPoint(CGPointMake(74.01, 37.95), controlPoint1: CGPointMake(73.99, 38.19), controlPoint2: CGPointMake(74.01, 38.07))
        bezier2Path.addLineToPoint(CGPointMake(32.5, 34.07))
        bezier2Path.addLineToPoint(CGPointMake(30.07, 23.96))
        bezier2Path.addCurveToPoint(CGPointMake(27, 20.64), controlPoint1: CGPointMake(29.7, 22.39), controlPoint2: CGPointMake(28.54, 21.13))
        bezier2Path.addLineToPoint(CGPointMake(9.03, 14.85))
        bezier2Path.addCurveToPoint(CGPointMake(6.38, 14.23), controlPoint1: CGPointMake(8.23, 14.46), controlPoint2: CGPointMake(7.34, 14.23))
        bezier2Path.addCurveToPoint(CGPointMake(0.23, 20.35), controlPoint1: CGPointMake(2.99, 14.23), controlPoint2: CGPointMake(0.23, 16.96))
        bezier2Path.addCurveToPoint(CGPointMake(6.38, 26.46), controlPoint1: CGPointMake(0.23, 23.72), controlPoint2: CGPointMake(2.99, 26.46))
        bezier2Path.addCurveToPoint(CGPointMake(10.4, 24.95), controlPoint1: CGPointMake(7.93, 26.46), controlPoint2: CGPointMake(9.31, 25.87))
        bezier2Path.addLineToPoint(CGPointMake(21.69, 28.58))
        bezier2Path.addCurveToPoint(CGPointMake(32.08, 71.94), controlPoint1: CGPointMake(21.69, 28.58), controlPoint2: CGPointMake(30.52, 66.16))
        bezier2Path.addCurveToPoint(CGPointMake(36.46, 83.18), controlPoint1: CGPointMake(32.87, 74.92), controlPoint2: CGPointMake(34.35, 79.34))
        bezier2Path.addCurveToPoint(CGPointMake(42.24, 79.83), controlPoint1: CGPointMake(37.96, 81.52), controlPoint2: CGPointMake(39.96, 80.32))
        bezier2Path.addCurveToPoint(CGPointMake(40.38, 75.48), controlPoint1: CGPointMake(41.38, 78.36), controlPoint2: CGPointMake(40.69, 76.79))
        bezier2Path.addLineToPoint(CGPointMake(85.63, 75.48))
        bezier2Path.addCurveToPoint(CGPointMake(90.07, 72.11), controlPoint1: CGPointMake(87.7, 75.48), controlPoint2: CGPointMake(89.52, 74.11))
        bezier2Path.addLineToPoint(CGPointMake(92.56, 60.05))
        bezier2Path.addCurveToPoint(CGPointMake(73.99, 38.31), controlPoint1: CGPointMake(82.05, 58.33), controlPoint2: CGPointMake(73.99, 49.25))
        bezier2Path.closePath()
        fillColor2.setFill()
        bezier2Path.fill()


        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(38.45, 83.55, 12.4, 13.4))
        fillColor2.setFill()
        ovalPath.fill()


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(69, 83.6, 13.4, 13.3))
        fillColor2.setFill()
        oval2Path.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(96.16, 20.18))
        bezier3Path.addCurveToPoint(CGPointMake(77.93, 38.31), controlPoint1: CGPointMake(86.11, 20.18), controlPoint2: CGPointMake(77.93, 28.32))
        bezier3Path.addCurveToPoint(CGPointMake(93.36, 56.16), controlPoint1: CGPointMake(77.93, 47.36), controlPoint2: CGPointMake(84.64, 54.81))
        bezier3Path.addCurveToPoint(CGPointMake(96.16, 56.45), controlPoint1: CGPointMake(94.28, 56.31), controlPoint2: CGPointMake(95.2, 56.45))
        bezier3Path.addCurveToPoint(CGPointMake(114.39, 38.31), controlPoint1: CGPointMake(106.21, 56.45), controlPoint2: CGPointMake(114.39, 48.31))
        bezier3Path.addCurveToPoint(CGPointMake(96.16, 20.18), controlPoint1: CGPointMake(114.39, 28.32), controlPoint2: CGPointMake(106.21, 20.18))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(108.61, 41.54))
        bezier3Path.addLineToPoint(CGPointMake(99.5, 41.54))
        bezier3Path.addLineToPoint(CGPointMake(99.5, 50.55))
        bezier3Path.addCurveToPoint(CGPointMake(96.51, 52.33), controlPoint1: CGPointMake(99.5, 51.74), controlPoint2: CGPointMake(98.5, 52.33))
        bezier3Path.addLineToPoint(CGPointMake(95.68, 52.33))
        bezier3Path.addCurveToPoint(CGPointMake(94.18, 52.15), controlPoint1: CGPointMake(95.08, 52.33), controlPoint2: CGPointMake(94.6, 52.26))
        bezier3Path.addCurveToPoint(CGPointMake(92.7, 50.55), controlPoint1: CGPointMake(93.22, 51.9), controlPoint2: CGPointMake(92.7, 51.38))
        bezier3Path.addLineToPoint(CGPointMake(92.7, 41.54))
        bezier3Path.addLineToPoint(CGPointMake(83.71, 41.54))
        bezier3Path.addCurveToPoint(CGPointMake(81.93, 38.69), controlPoint1: CGPointMake(82.54, 41.54), controlPoint2: CGPointMake(81.96, 40.58))
        bezier3Path.addCurveToPoint(CGPointMake(81.92, 38.58), controlPoint1: CGPointMake(81.93, 38.65), controlPoint2: CGPointMake(81.92, 38.62))
        bezier3Path.addLineToPoint(CGPointMake(81.92, 38.17))
        bezier3Path.addCurveToPoint(CGPointMake(83.71, 35.2), controlPoint1: CGPointMake(81.92, 36.19), controlPoint2: CGPointMake(82.52, 35.2))
        bezier3Path.addLineToPoint(CGPointMake(92.7, 35.2))
        bezier3Path.addLineToPoint(CGPointMake(92.7, 26.07))
        bezier3Path.addCurveToPoint(CGPointMake(95.68, 24.29), controlPoint1: CGPointMake(92.7, 24.89), controlPoint2: CGPointMake(93.69, 24.29))
        bezier3Path.addLineToPoint(CGPointMake(96.51, 24.29))
        bezier3Path.addCurveToPoint(CGPointMake(99.5, 26.07), controlPoint1: CGPointMake(98.49, 24.29), controlPoint2: CGPointMake(99.5, 24.89))
        bezier3Path.addLineToPoint(CGPointMake(99.5, 35.2))
        bezier3Path.addLineToPoint(CGPointMake(108.61, 35.2))
        bezier3Path.addCurveToPoint(CGPointMake(110.39, 38.17), controlPoint1: CGPointMake(109.8, 35.2), controlPoint2: CGPointMake(110.39, 36.19))
        bezier3Path.addLineToPoint(CGPointMake(110.39, 38.58))
        bezier3Path.addCurveToPoint(CGPointMake(108.61, 41.54), controlPoint1: CGPointMake(110.4, 40.56), controlPoint2: CGPointMake(109.8, 41.54))
        bezier3Path.closePath()
        fillColor2.setFill()
        bezier3Path.fill()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
