# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'YouTube' do
  pod 'YouTubePlayer'
end
