# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'BasicBannerAd' do
	pod 'Google-Mobile-Ads-SDK', '~> 7.5'
end
