# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'MyArcGIS' do
  pod 'ArcGIS-Runtime-SDK-iOS', '100.0-beta1' 
end
